# Generated by Django 6.0.6 on 2026-06-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default='White', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(default='Modern', max_length=100),
        ),
    ]
